#define H_RES_ACT_FRAMES                320
#define H_FRONT_PORCH_FRAMES            8
#define H_SYNC_PULSE_FRAMES             48
#define H_BACK_PORCH_FRAMES             24


#define V_RES_ACT_FRAMES                480
#define V_FRONT_PORCH_FRAMES            10
#define V_SYNC_PULSE_FRAMES             2
#define V_BACK_PORCH_FRAMES             33

#define H_BLANKING_FRAMES               (H_FRONT_PORCH_FRAMES + H_SYNC_PULSE_FRAMES + H_BACK_PORCH_FRAMES)
#define V_BLANKING_FRAMES               (V_FRONT_PORCH_FRAMES + V_SYNC_PULSE_FRAMES + V_BACK_PORCH_FRAMES)

#define RGB_RES_BITS                    3
#define H_SYNC_V_SYNC_BITS              2
#define ACTIVE_BITS                     (RGB_RES_BITS + H_SYNC_V_SYNC_BITS)

#define ROW_ACTIVE_BITS                 (H_RES_ACT_FRAMES * ACTIVE_BITS) // 320 frames * 5 bits (01011 --> 0R, 1G, 0B, 1H, 1V)
#define ROW_FRONT_PORCH_BITS            (H_FRONT_PORCH_FRAMES * H_SYNC_V_SYNC_BITS) //only H/V-SYNC bits
#define ROW_SYNC_PULSE_BITS             (H_SYNC_PULSE_FRAMES * H_SYNC_V_SYNC_BITS)
#define ROW_BACK_PORCH_BITS             (H_BACK_PORCH_FRAMES * H_SYNC_V_SYNC_BITS)

#define V_ACTIVE_ROW_TOTAL_BITS         (ROW_ACTIVE_BITS + ROW_FRONT_PORCH_BITS + ROW_SYNC_PULSE_BITS + ROW_BACK_PORCH_BITS)
#define V_ACTIVE_ROW_TOTAL_BYTES        (V_ACTIVE_ROW_TOTAL_BITS / 8)

#define V_BLANKING_ROW_TOTAL_BITS       ((H_RES_ACT_FRAMES + H_BLANKING_FRAMES) * 2) //total row frames == 400 * 2bit (h/v-sync) == 800
#define V_BLANKING_ROW_TOTAL_BYTES      (V_BLANKING_ROW_TOTAL_BITS / 8)

#define TOTAL_ACTIVE_FRAMES_BYTES       (V_ACTIVE_ROW_TOTAL_BYTES * V_RES_ACT_FRAMES)
#define TOTAL_BLANKING_FRAMES_BYTES     (V_BLANKING_ROW_TOTAL_BYTES * V_BLANKING_FRAMES)

#define TOTAL_BYTES                     (TOTAL_ACTIVE_FRAMES_BYTES + TOTAL_BLANKING_FRAMES_BYTES)
#define TOTAL_FRAMES                    ((H_RES_ACT_FRAMES + H_BLANKING_FRAMES) * (V_RES_ACT_FRAMES + V_BLANKING_FRAMES))

#define ACTIVE_CHUNK_LEN                V_RES_ACT_FRAMES
#define BLANKING_CHUNK_LEN              V_BLANKING_FRAMES
#define ACTIVE_SINGLE_CHUNK_SIZE        V_ACTIVE_ROW_TOTAL_BYTES
#define BLANKING_SINGLE_CHUNK_SIZE      V_BLANKING_ROW_TOTAL_BYTES

#define H_RES                           H_RES_ACT_FRAMES
#define V_RES                           V_RES_ACT_FRAMES